'use client'

import { useState } from 'react'
import JSZip from 'jszip'
import { saveAs } from 'file-saver'
import { analytics } from '@/lib/analytics'

interface SimpleExportButtonProps {
  projectId: string
  projectName: string
  projectCode: string
  projectType: string
  onSuccess?: () => void
  onError?: (error: string) => void
  size?: 'default' | 'icon'
}

export default function SimpleExportButton({
  projectId,
  projectName,
  projectCode,
  projectType,
  onSuccess,
  onError,
  size = 'default'
}: SimpleExportButtonProps) {
  const [showModal, setShowModal] = useState(false)
  const [loading, setLoading] = useState(false)
  const [loadingMessage, setLoadingMessage] = useState('Processing...')

  // Generate package.json content
  const generatePackageJson = () => {
    return JSON.stringify({
      name: projectName.toLowerCase().replace(/\s+/g, '-'),
      version: '1.0.0',
      description: `${projectName} - Generated by BuildFlow`,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint'
      },
      dependencies: {
        'next': '^14.0.0',
        'react': '^18.0.0',
        'react-dom': '^18.0.0'
      },
      devDependencies: {
        '@types/node': '^20.0.0',
        '@types/react': '^18.0.0',
        '@types/react-dom': '^18.0.0',
        'typescript': '^5.0.0',
        'tailwindcss': '^3.0.0',
        'autoprefixer': '^10.0.0',
        'postcss': '^8.0.0'
      }
    }, null, 2)
  }

  // Generate README.md content
  const generateReadme = () => {
    return `# ${projectName}

Generated with [BuildFlow](https://buildflow-ai.app) - AI-Powered Code Generation

## 🚀 Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) in your browser.

---

Made with ❤️ by BuildFlow
`
  }

  // Generate layout.tsx
  const generateLayout = () => {
    return `import './globals.css'

export const metadata = {
  title: '${projectName}',
  description: 'Generated by BuildFlow',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`
  }

  // Generate globals.css
  const generateGlobalsCss = () => {
    return `@tailwind base;
@tailwind components;
@tailwind utilities;`
  }

  // Generate tailwind.config.js
  const generateTailwindConfig = () => {
    return `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`
  }

  // Generate .gitignore
  const generateGitignore = () => {
    return `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts`
  }

  // Download as ZIP
  const downloadZip = async () => {
    try {
      setLoading(true)
      setLoadingMessage('Creating ZIP file...')
      const zip = new JSZip()

      // Create app directory structure
      const appFolder = zip.folder('app')
      if (appFolder) {
        appFolder.file('page.tsx', projectCode)
        appFolder.file('layout.tsx', generateLayout())
        appFolder.file('globals.css', generateGlobalsCss())
      }

      // Add public folder
      zip.folder('public')

      // Add configuration files
      zip.file('package.json', generatePackageJson())
      zip.file('README.md', generateReadme())
      zip.file('tailwind.config.js', generateTailwindConfig())
      zip.file('.gitignore', generateGitignore())

      // Generate ZIP file
      const content = await zip.generateAsync({ type: 'blob' })
      
      // Download
      const fileName = `${projectName.toLowerCase().replace(/\s+/g, '-')}.zip`
      saveAs(content, fileName)

      // Track export analytics
      analytics.projectExported('zip')

      setShowModal(false)
      onSuccess?.()
    } catch (error) {
      console.error('Export error:', error)
      onError?.('Failed to export project')
    } finally {
      setLoading(false)
    }
  }

  // Copy code to clipboard
  const copyToClipboard = async () => {
    try {
      setLoading(true)
      setLoadingMessage('Copying to clipboard...')
      await navigator.clipboard.writeText(projectCode)
      
      // Track export analytics
      analytics.projectExported('copy')
      
      alert('Code copied to clipboard!')
      setShowModal(false)
      onSuccess?.()
    } catch (error) {
      console.error('Copy error:', error)
      onError?.('Failed to copy code')
    } finally {
      setLoading(false)
    }
  }

  // Download single file
  const downloadSingleFile = () => {
    try {
      setLoading(true)
      setLoadingMessage('Downloading file...')
      const blob = new Blob([projectCode], { type: 'text/plain;charset=utf-8' })
      const fileName = `${projectName.toLowerCase().replace(/\s+/g, '-')}.tsx`
      saveAs(blob, fileName)
      
      // Track export analytics
      analytics.projectExported('file')
      
      setShowModal(false)
      onSuccess?.()
    } catch (error) {
      console.error('Download error:', error)
      onError?.('Failed to download file')
    } finally {
      setLoading(false)
    }
  }

  // Push to GitHub
  const pushToGitHub = async () => {
    try {
      setLoading(true)
      setLoadingMessage('Creating GitHub repository...')

      const response = await fetch('/api/github/create-repo', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          projectId,
          projectName,
          projectCode,
          description: `${projectName} - Generated by BuildFlow`,
          files: {
            'app/page.tsx': projectCode,
            'app/layout.tsx': generateLayout(),
            'app/globals.css': generateGlobalsCss(),
            'package.json': generatePackageJson(),
            'README.md': generateReadme(),
            'tailwind.config.js': generateTailwindConfig(),
            '.gitignore': generateGitignore(),
          }
        }),
      })

      const data = await response.json()

      if (!response.ok) {
        // Check if user needs to connect GitHub
        if (data.needsGithubConnection) {
          const connect = confirm(
            '🔗 GitHub not connected!\n\n' +
            'To export to your own GitHub account, you need to connect your GitHub account.\n\n' +
            'Click OK to connect GitHub, or Cancel to skip.'
          )
          if (connect) {
            // Redirect to GitHub OAuth flow with current project context
            window.location.href = `/api/auth/github?projectId=${projectId}`
          }
          return
        }
        throw new Error(data.error || 'Failed to create repository')
      }

      // Success! Show the repo URL
      alert(`✅ Repository created successfully!\n\n${data.repoUrl}\n\nOpening in new tab...`)
      window.open(data.repoUrl, '_blank')
      
      // Track export analytics
      analytics.projectExported('github')
      
      setShowModal(false)
      onSuccess?.()
    } catch (error: any) {
      console.error('GitHub error:', error)
      const errorMessage = error.message || 'Failed to create GitHub repository'
      alert(`❌ Error: ${errorMessage}`)
      onError?.(errorMessage)
    } finally {
      setLoading(false)
    }
  }

  // Icon mode for toolbar
  if (size === 'icon') {
    return (
      <>
        <button
          onClick={() => setShowModal(true)}
          className="p-2 text-gray-400 hover:text-white hover:bg-gray-800 rounded-lg transition"
          title="Export Project"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
        </button>

        {/* Shared modal and loading */}
        {showModal && renderModal()}
        {loading && renderLoading()}
      </>
    )
  }

  // Helper functions for rendering shared components
  function renderModal() {
    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
        <div className="bg-white rounded-3xl shadow-2xl max-w-md w-full overflow-hidden">
          {/* Header */}
          <div className="bg-gradient-to-r from-green-600 to-emerald-600 text-white p-6">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="font-bold text-2xl flex items-center gap-2">
                  <span>📦</span>
                  Export Project
                </h3>
                <p className="text-sm text-green-100 mt-1">
                  {projectName}
                </p>
              </div>
              <button
                onClick={() => setShowModal(false)}
                className="text-white hover:bg-white/20 rounded-lg p-2 transition-colors"
              >
                <span className="text-2xl">✕</span>
              </button>
            </div>
          </div>

          {/* Options */}
          <div className="p-6 space-y-3">
            {/* Download ZIP */}
            <button
              onClick={downloadZip}
              disabled={loading}
              className="w-full flex items-center gap-4 p-4 hover:bg-gray-50 rounded-xl transition-colors text-left group border-2 border-gray-100 hover:border-green-200 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <div className="bg-gradient-to-br from-blue-500 to-blue-600 p-3 rounded-xl group-hover:scale-110 transition-transform">
                <span className="text-white text-2xl">📁</span>
              </div>
              <div className="flex-1">
                <div className="font-bold text-gray-900 text-lg">Download ZIP</div>
                <div className="text-sm text-gray-600">
                  Complete project with all files
                </div>
              </div>
            </button>

            {/* Copy Code */}
            <button
              onClick={copyToClipboard}
              disabled={loading}
              className="w-full flex items-center gap-4 p-4 hover:bg-gray-50 rounded-xl transition-colors text-left group border-2 border-gray-100 hover:border-purple-200 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <div className="bg-gradient-to-br from-purple-500 to-purple-600 p-3 rounded-xl group-hover:scale-110 transition-transform">
                <span className="text-white text-2xl">📋</span>
              </div>
              <div className="flex-1">
                <div className="font-bold text-gray-900 text-lg">Copy Code</div>
                <div className="text-sm text-gray-600">
                  Copy to clipboard
                </div>
              </div>
            </button>

            {/* Download Single File */}
            <button
              onClick={downloadSingleFile}
              disabled={loading}
              className="w-full flex items-center gap-4 p-4 hover:bg-gray-50 rounded-xl transition-colors text-left group border-2 border-gray-100 hover:border-orange-200 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <div className="bg-gradient-to-br from-orange-500 to-orange-600 p-3 rounded-xl group-hover:scale-110 transition-transform">
                <span className="text-white text-2xl">📄</span>
              </div>
              <div className="flex-1">
                <div className="font-bold text-gray-900 text-lg">Download File</div>
                <div className="text-sm text-gray-600">
                  Single .tsx file only
                </div>
              </div>
            </button>

            {/* Push to GitHub */}
            <button
              onClick={pushToGitHub}
              disabled={loading}
              className="w-full flex items-center gap-4 p-4 hover:bg-gray-50 rounded-xl transition-colors text-left group border-2 border-gray-100 hover:border-gray-900 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <div className="bg-gradient-to-br from-gray-800 to-gray-900 p-3 rounded-xl group-hover:scale-110 transition-transform">
                <span className="text-white text-2xl">🚀</span>
              </div>
              <div className="flex-1">
                <div className="font-bold text-gray-900 text-lg">Push to GitHub</div>
                <div className="text-sm text-gray-600">
                  Create repository and push code
                </div>
              </div>
            </button>
          </div>

          {/* Footer */}
          <div className="border-t border-gray-100 p-4 bg-gray-50">
            <p className="text-xs text-gray-600 text-center">
              💡 Tip: Use ZIP download for complete setup
            </p>
          </div>
        </div>
      </div>
    )
  }

  function renderLoading() {
    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-[60]">
        <div className="bg-white rounded-2xl p-8 text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-4 border-green-600 mx-auto mb-4"></div>
          <p className="text-lg font-medium text-gray-900">{loadingMessage}</p>
          <p className="text-sm text-gray-600 mt-2">Please wait...</p>
        </div>
      </div>
    )
  }

  // Default rendering
  return (
    <>
      {/* Simple Export Button */}
      <button
        onClick={() => setShowModal(true)}
        className="flex flex-col items-center gap-1 py-3 bg-green-50 hover:bg-green-100 text-green-600 rounded-xl transition-all hover:scale-105"
        title="Export Project"
      >
        <span className="text-xl">📦</span>
        <span className="text-xs font-medium">Export</span>
      </button>

      {/* Modal */}
      {showModal && renderModal()}

      {/* Loading Overlay */}
      {loading && renderLoading()}
    </>
  )
}