// Security enhancements for SSRF, path, token, logging
export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { decrypt } from '@/lib/encryption';

function isValidRepoName(name: string) {
  return /^[a-z0-9\-]{1,100}$/.test(name);
}
function isValidBranchName(name: string) {
  return /^[a-zA-Z0-9_.\-]{1,40}$/.test(name);
}
function isValidToken(token: string) {
  return typeof token === 'string' && token.length > 20 && /^[a-zA-Z0-9\-_]+$/.test(token);
}
function isValidPath(path: string) {
  if (!/^[A-Za-z0-9._\-\/]+$/.test(path) || path.includes('..') || path.startsWith('/') || path.length === 0) return false;
  const forbiddenFiles = ['.env', '.htaccess', '.gitignore', '.npmrc'];
  for (const forbidden of forbiddenFiles) if (path.endsWith(forbidden) || path === forbidden) return false;
  return true;
}

function handleRouteError(error: unknown, context?: string) {
  let message = 'Unknown error';
  if (typeof error === 'object' && error !== null && 'message' in error) message = (error as Error).message;
  else if (typeof error === 'string') message = error;
  if (context) console.error(`[Create Repo ERROR] ${context}:`, error);
  else console.error('[Create Repo ERROR]:', error);
  return NextResponse.json({ error: 'Unexpected error. Please retry or contact support.' }, { status: 500 });
}

export async function POST(request: NextRequest) {
  try {
    // Check authentication
    const session = await getServerSession(authOptions);
    if (!session?.user?.email) {
      console.warn('Missing authentication for create repo');
      return NextResponse.json(
        { error: 'Unauthorized - Please sign in' },
        { status: 401 }
      );
    }
    // Get user's GitHub token from database
    const user = await prisma.user.findUnique({
      where: { email: session.user.email },
      select: { githubAccessToken: true, githubUsername: true },
    });
    if (!user?.githubAccessToken) {
      console.warn(`No GitHub token for user ${session.user.email}`);
      return NextResponse.json(
        {
          error: 'GitHub not connected. Please connect your GitHub account to export projects to your own repositories.',
          needsGithubConnection: true,
        },
        { status: 400 }
      );
    }
    const githubToken = decrypt(user.githubAccessToken);
    if (!isValidToken(githubToken)) {
      console.warn('Invalid GitHub token');
      return NextResponse.json(
        { error: 'Invalid GitHub token detected.' },
        { status: 400 }
      );
    }
    // Parse request body
    const body = await request.json();
    const { projectId, projectName, description, files } = body;
    let finalProjectName = projectName;
    let finalDescription = description;
    let finalFiles = files;
    if (projectId) {
      const project = await prisma.project.findUnique({ where: { id: projectId } });
      if (!project) {
        return NextResponse.json(
          { error: 'Project not found' },
          { status: 404 }
        );
      }
      finalProjectName = project.name;
      finalDescription = project.description || `${project.name} - Generated by BuildFlow`;
      finalFiles = {
        'app/page.tsx': project.code || '',
        'app/layout.tsx': `import './globals.css'\nexport const metadata = {\n  title: '${project.name}',\n  description: '${project.description || 'Generated by BuildFlow'}',\n}\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (<html lang="en"><body>{children}</body></html>); }`,
        'app/globals.css': `@tailwind base;\n@tailwind components;\n@tailwind utilities;`,
        'package.json': JSON.stringify({
          name: project.name.toLowerCase().replace(/\s+/g, '-'),
          version: '1.0.0',
          description: project.description || `${project.name} - Generated by BuildFlow`,
          scripts: { dev: 'next dev', build: 'next build', start: 'next start', lint: 'next lint' },
          dependencies: { 'next': '^14.0.0', 'react': '^18.0.0', 'react-dom': '^18.0.0' },
          devDependencies: {
            '@types/node': '^20.0.0', '@types/react': '^18.0.0', '@types/react-dom': '^18.0.0', 'typescript': '^5.0.0', 'tailwindcss': '^3.0.0', 'autoprefixer': '^10.0.0', 'postcss': '^8.0.0',
          },
        }, null, 2),
        'tailwind.config.js': `/** @type {import('tailwindcss').Config} */\nmodule.exports = {\n  content: [\n    './pages/**/*.{js,ts,jsx,tsx,mdx}',\n    './components/**/*.{js,ts,jsx,tsx,mdx}',\n    './app/**/*.{js,ts,jsx,tsx,mdx}',\n  ],\n  theme: { extend: {} },\n  plugins: [],\n}`,
        'README.md': `# ${project.name}\n\nGenerated with [BuildFlow](https://buildflow-ai.app)\n\n## Getting Started\n\n\`

npm install\nnpm run dev\
\`
\nOpen [http://localhost:3000](http://localhost:3000) in your browser.\n\n---\n\nMade with ❤️ by BuildFlow`,
        '.gitignore': `# dependencies\n/node_modules\n/.pnp\n.pnp.js\n# testing\n/coverage\n# next.js\n/.next/\n/out/\n# production\n/build\n# misc\n.DS_Store\n*.pem\n# debug\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\n# local env files\n.env*.local\n# vercel\n.vercel\n# typescript\n*.tsbuildinfo\nnext-env.d.ts`,
      };
    }
    if (!finalProjectName || typeof finalProjectName !== 'string') {
      console.warn('Missing final project name');
      return NextResponse.json(
        { error: 'Project name is required' },
        { status: 400 }
      );
    }
    const repoName = finalProjectName.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
    if (!isValidRepoName(repoName)) {
      console.warn(`Invalid repo name generated: ${repoName}`);
      return NextResponse.json(
        { error: 'Repository name is invalid.' },
        { status: 400 }
      );
    }
    // Step 1: Create the repository
    console.log('Creating GitHub repository:', repoName);
    const createRepoResponse = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        'Authorization': `token ${githubToken}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: repoName,
        description: finalDescription || `${finalProjectName} - Generated by BuildFlow`,
        private: false,
        auto_init: true,
      }),
    });
    if (!createRepoResponse.ok) {
      const error = await createRepoResponse.json();
      console.error('GitHub API error:', error);
      if (error.errors && error.errors[0]?.message?.includes('already exists')) {
        return NextResponse.json(
          { error: `Repository '${repoName}' already exists in your GitHub account. Please choose a different name.` },
          { status: 409 }
        );
      }
      if (error.message?.includes('Bad credentials') || createRepoResponse.status === 401) {
        if (user?.githubAccessToken) {
          await prisma.user.update({ where: { email: session.user.email }, data: { githubAccessToken: null, githubUsername: null } });
        }
        return NextResponse.json(
          { error: 'GitHub authorization expired. Please reconnect your GitHub account.', needsGithubConnection: true },
          { status: 401 }
        );
      }
      return NextResponse.json(
        { error: error.message || 'Failed to create repository' },
        { status: createRepoResponse.status }
      );
    }
    const repo = await createRepoResponse.json();
    console.log('Repository created:', repo.html_url);
    // Step 2: Upload files to the repository
    if (finalFiles && typeof finalFiles === 'object' && Object.keys(finalFiles).length > 0) {
      console.log('Uploading files to repository...');
      const defaultBranch = repo.default_branch || 'main';
      for (const [path, content] of Object.entries(finalFiles)) {
        if (!isValidPath(path)) {
          console.warn(`Blocked invalid file path: ${path}`);
          continue;
        }
        try {
          const uploadResponse = await fetch(
            `https://api.github.com/repos/${repo.owner.login}/${repoName}/contents/${path}`,
            {
              method: 'PUT',
              headers: {
                'Authorization': `token ${githubToken}`,
                'Accept': 'application/vnd.github.v3+json',
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                message: `Add ${path}`,
                content: Buffer.from(content as string).toString('base64'),
                branch: defaultBranch,
              }),
            }
          );
          if (!uploadResponse.ok) {
            const uploadError = await uploadResponse.json();
            console.error(`Failed to upload ${path}:`, uploadError);
          } else {
            console.log(`Uploaded: ${path}`);
          }
        } catch (uploadError) {
          handleRouteError(uploadError, `Upload file ${path}`);
        }
      }
    }
    return NextResponse.json({
      success: true,
      repoUrl: repo.html_url,
      repoName: repoName,
      owner: repo.owner.login,
      message: `Repository created successfully in ${repo.owner.login}'s GitHub!`,
    });
  } catch (error: any) {
    return handleRouteError(error, 'create-repo POST');
  }
}
