export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export async function POST(request: NextRequest) {
  try {
    // Check authentication
    const session = await getServerSession(authOptions)
    
    if (!session?.user?.email) {
      return NextResponse.json(
        { error: 'Unauthorized - Please sign in' },
        { status: 401 }
      )
    }

    // Get user's GitHub token from database
    const user = await prisma.user.findUnique({
      where: { email: session.user.email },
      select: { githubAccessToken: true, githubUsername: true }
    })

    const githubToken = user?.githubAccessToken
    
    // Require user to have connected their own GitHub account
    if (!githubToken) {
      return NextResponse.json(
        { 
          error: 'GitHub not connected. Please sign in with GitHub to connect your account and export projects to your own repositories.',
          needsGithubConnection: true
        },
        { status: 400 }
      )
    }

    // Parse request body
    const body = await request.json()
    const { projectName, description, files } = body

    if (!projectName) {
      return NextResponse.json(
        { error: 'Project name is required' },
        { status: 400 }
      )
    }

    // Create repository name (lowercase, no spaces)
    const repoName = projectName.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')

    // Step 1: Create the repository
    console.log('Creating GitHub repository:', repoName)
    
    const createRepoResponse = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        'Authorization': `token ${githubToken}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: repoName,
        description: description || `${projectName} - Generated by BuildFlow`,
        private: false,
        auto_init: true, // Initialize with README
      }),
    })

    if (!createRepoResponse.ok) {
      const error = await createRepoResponse.json()
      console.error('GitHub API error:', error)
      
      // Handle specific errors
      if (error.errors && error.errors[0]?.message?.includes('already exists')) {
        return NextResponse.json(
          { error: `Repository '${repoName}' already exists in your GitHub account. Please choose a different name.` },
          { status: 409 }
        )
      }

      // Handle token expired/invalid
      if (error.message?.includes('Bad credentials') || createRepoResponse.status === 401) {
        // Clear the invalid token
        if (user?.githubAccessToken) {
          await prisma.user.update({
            where: { email: session.user.email },
            data: { githubAccessToken: null, githubUsername: null }
          })
        }
        return NextResponse.json(
          { 
            error: 'GitHub authorization expired. Please reconnect your GitHub account.',
            needsGithubConnection: true
          },
          { status: 401 }
        )
      }
      
      return NextResponse.json(
        { error: error.message || 'Failed to create repository' },
        { status: createRepoResponse.status }
      )
    }

    const repo = await createRepoResponse.json()
    console.log('Repository created:', repo.html_url)

    // Step 2: Upload files to the repository
    if (files && Object.keys(files).length > 0) {
      console.log('Uploading files to repository...')
      
      // Get the default branch (usually 'main' or 'master')
      const defaultBranch = repo.default_branch || 'main'
      
      // Upload each file
      for (const [path, content] of Object.entries(files)) {
        try {
          const uploadResponse = await fetch(
            `https://api.github.com/repos/${repo.owner.login}/${repoName}/contents/${path}`,
            {
              method: 'PUT',
              headers: {
                'Authorization': `token ${githubToken}`,
                'Accept': 'application/vnd.github.v3+json',
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                message: `Add ${path}`,
                content: Buffer.from(content as string).toString('base64'),
                branch: defaultBranch,
              }),
            }
          )

          if (!uploadResponse.ok) {
            const uploadError = await uploadResponse.json()
            console.error(`Failed to upload ${path}:`, uploadError)
          } else {
            console.log(`Uploaded: ${path}`)
          }
        } catch (uploadError) {
          console.error(`Error uploading ${path}:`, uploadError)
        }
      }
    }

    // Return success with repository URL
    return NextResponse.json({
      success: true,
      repoUrl: repo.html_url,
      repoName: repoName,
      owner: repo.owner.login,
      message: `Repository created successfully in ${repo.owner.login}'s GitHub!`,
    })

  } catch (error: any) {
    console.error('GitHub integration error:', error)
    return NextResponse.json(
      { error: error.message || 'Internal server error' },
      { status: 500 }
    )
  }
}
