// lib/downloadProjectZip.ts
// Bundles all generated project files into a ZIP and triggers a browser download.
//
// HTML sites: includes a self-contained Node.js/Express server so the site
// works completely independently — no BuildFlow account required.
// Any absolute buildflow-ai.app API URLs are rewritten back to relative paths
// so they resolve against the local server instead.
//
// Next.js/React sites: standard project bundle (npm install + deploy).

import JSZip from "jszip";
import { generateServerBundle } from "@/lib/selfContainedServer";

// Domains we may have injected as absolute prefixes in the save route.
// Strip them back to relative paths so the local Express server handles them.
const BUILDFLOW_ORIGINS = [
  "https://buildflow-ai.app",
  "http://localhost:3000",
];

function stripBuildFlowOrigin(content: string): string {
  let out = content;
  for (const origin of BUILDFLOW_ORIGINS) {
    // e.g. "https://buildflow-ai.app/api/" → "/api/"
    out = out.replaceAll(origin + "/api/", "/api/");
  }
  return out;
}

/**
 * Creates a ZIP of all project files and triggers a browser download.
 *
 * @param files       - Flat map of { "index.html": "...", "style.css": "..." }
 * @param projectName - Used as the ZIP filename (sanitized)
 */
export async function downloadProjectZip(
  files: Record<string, string>,
  projectName: string
): Promise<void> {
  const zip = new JSZip();

  const isHtml = Object.keys(files).some((p) => p.endsWith(".html"));

  if (isHtml) {
    // ── Self-contained HTML site ──────────────────────────────────────────────

    const readme = `# ${projectName}

Generated by BuildFlow AI — https://buildflow-ai.app

## Running locally (fully self-contained — no BuildFlow needed)

Requires Node.js 16+. Get it at https://nodejs.org if you don't have it.

\`\`\`
npm install
node server.js
\`\`\`

Then open http://localhost:3000 in your browser.

## What's included

- All HTML/CSS/JS pages
- \`server.js\` — lightweight Node.js server that handles:
  - Contact form submissions (saved to \`data/db.json\`)
  - User registration & login (JWT auth, stored in \`data/db.json\`)
- \`data/db.json\` — created on first run; all your form data lives here

## Deploy to a Node.js host (Railway, Render, Fly.io, Heroku)

1. Push this folder to a Git repo
2. Set the start command to \`node server.js\`
3. Done — forms and auth work on your own server

## Deploy as static-only (Netlify, Vercel, GitHub Pages)

Upload all files **except** \`server.js\`, \`package.json\`, and \`data/\`.
Forms and auth will not work in static mode without a separate backend.
`;

    zip.file("README.md", readme);

    // Add all project files, stripping any absolute BuildFlow API URLs
    // so form fetch() calls resolve against the local Express server
    for (const [filePath, content] of Object.entries(files)) {
      // Skip internal pipeline artifacts (e.g. _nav_html, _footer_html)
      if (filePath.startsWith("_")) continue;
      const normalized = filePath.replace(/\\/g, "/");
      const isApiConsumer = filePath.endsWith(".html") || filePath.endsWith(".js");
      zip.file(normalized, isApiConsumer ? stripBuildFlowOrigin(content) : content);
    }

    // Bundle the self-contained server
    const serverFiles = generateServerBundle(projectName);
    for (const [filePath, content] of Object.entries(serverFiles)) {
      zip.file(filePath, content);
    }

  } else {
    // ── Next.js / React project ───────────────────────────────────────────────

    const readme = `# ${projectName}

Generated by BuildFlow AI — https://buildflow-ai.app

## Getting started

\`\`\`
npm install
cp .env.example .env.local
# Add your DATABASE_URL and NEXTAUTH_SECRET
npx prisma db push
npm run dev
\`\`\`

This is production-ready code that requires a developer to add database
credentials and deploy. It is not a running application out of the box.
`;

    zip.file("README.md", readme);

    for (const [filePath, content] of Object.entries(files)) {
      if (filePath.startsWith("_")) continue;
      zip.file(filePath.replace(/\\/g, "/"), content);
    }
  }

  const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE" });

  const safeName =
    projectName
      .trim()
      .replace(/[^a-z0-9]+/gi, "-")
      .replace(/^-+|-+$/g, "")
      .toLowerCase() || "project";

  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${safeName}.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
