'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import DeployToVercel from '@/components/DeployToVercel';

interface Project {
  id: string;
  name: string;
  description?: string;
  code: string;
  type: string;
}

export default function ProjectPageExample({ project }: { project: Project }) {
  const [githubRepoName, setGithubRepoName] = useState<string | undefined>();
  const [isExporting, setIsExporting] = useState(false);

  const handleGithubExport = async () => {
    try {
      setIsExporting(true);

      // Call the GitHub export API
      const response = await fetch('/api/github/create-repo', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          projectId: project.id,
          projectName: project.name,
          projectCode: project.code,
          description: `${project.name} - Generated by BuildFlow`,
          files: {
            'app/page.tsx': project.code,
            'app/layout.tsx': generateLayout(),
            'app/globals.css': generateGlobalsCss(),
            'package.json': generatePackageJson(project.name),
            'README.md': generateReadme(project.name),
            'tailwind.config.js': generateTailwindConfig(),
            '.gitignore': generateGitignore(),
          }
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        if (data.needsGithubConnection) {
          const connect = confirm(
            '🔗 GitHub not connected!\n\n' +
            'To export to your own GitHub account, you need to connect your GitHub account.\n\n' +
            'Click OK to connect GitHub, or Cancel to skip.'
          );
          if (connect) {
            window.location.href = `/api/auth/github?projectId=${project.id}`;
          }
          return;
        }
        throw new Error(data.error || 'Failed to create repository');
      }

      // Extract repo name from the repo URL
      // Format: https://github.com/username/repo-name
      const repoName = data.repoUrl.split('/').pop();
      setGithubRepoName(repoName);

      alert(`✅ Repository created successfully!\n\n${data.repoUrl}`);
      window.open(data.repoUrl, '_blank');

    } catch (error: any) {
      console.error('GitHub export error:', error);
      alert(`❌ Error: ${error.message || 'Failed to export to GitHub'}`);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-900 text-white p-6">
      <div className="max-w-4xl mx-auto space-y-6">
        {/* Project Header */}
        <div className="bg-gray-800 rounded-2xl p-6 border border-gray-700">
          <h1 className="text-3xl font-bold mb-2">{project.name}</h1>
          {project.description && (
            <p className="text-gray-400">{project.description}</p>
          )}
        </div>

        {/* Export and Deploy Section */}
        <div className="bg-gray-800 rounded-2xl p-6 border border-gray-700">
          <h2 className="text-xl font-bold mb-4">Export & Deploy</h2>
          
          <div className="space-y-4">
            {/* Step 1: Export to GitHub */}
            <div className="flex items-start gap-4">
              <div className="flex-shrink-0 w-8 h-8 rounded-full bg-purple-600 flex items-center justify-center font-bold">
                1
              </div>
              <div className="flex-1">
                <h3 className="font-semibold mb-2">Export to GitHub</h3>
                <p className="text-sm text-gray-400 mb-3">
                  First, push your code to a GitHub repository
                </p>
                <Button 
                  onClick={handleGithubExport}
                  disabled={isExporting || !!githubRepoName}
                  className="gap-2"
                  variant="outline"
                >
                  {isExporting ? (
                    <>Loading...</>
                  ) : githubRepoName ? (
                    <>✓ Exported to {githubRepoName}</>
                  ) : (
                    <>🚀 Export to GitHub</>
                  )}
                </Button>
              </div>
            </div>

            {/* Step 2: Deploy to Vercel */}
            <div className="flex items-start gap-4">
              <div className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center font-bold ${
                githubRepoName ? 'bg-purple-600' : 'bg-gray-600'
              }`}>
                2
              </div>
              <div className="flex-1">
                <h3 className="font-semibold mb-2">Deploy to Vercel</h3>
                <p className="text-sm text-gray-400 mb-3">
                  Deploy your GitHub repository to Vercel
                </p>
                <DeployToVercel
                  projectId={project.id}
                  projectName={project.name}
                  githubRepoName={githubRepoName}
                />
              </div>
            </div>
          </div>

          {/* Info Message */}
          {!githubRepoName && (
            <div className="mt-4 p-4 bg-blue-900/20 border border-blue-700 rounded-lg">
              <p className="text-sm text-blue-300">
                💡 Tip: You must export to GitHub before deploying to Vercel
              </p>
            </div>
          )}
        </div>

        {/* Code Preview */}
        <div className="bg-gray-800 rounded-2xl p-6 border border-gray-700">
          <h2 className="text-xl font-bold mb-4">Code Preview</h2>
          <div className="bg-gray-900 rounded-lg p-4 overflow-x-auto max-h-[400px]">
            <pre className="text-sm text-gray-300">
              <code>{project.code}</code>
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}

// Helper functions to generate project files
function generateLayout() {
  return `export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`;
}

function generateGlobalsCss() {
  return `@tailwind base;
@tailwind components;
@tailwind utilities;`;
}

function generatePackageJson(projectName: string) {
  return JSON.stringify({
    name: projectName.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    description: `${projectName} - Generated by BuildFlow`,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint'
    },
    dependencies: {
      'next': '^14.0.0',
      'react': '^18.0.0',
      'react-dom': '^18.0.0'
    },
    devDependencies: {
      '@types/node': '^20.0.0',
      '@types/react': '^18.0.0',
      '@types/react-dom': '^18.0.0',
      'autoprefixer': '^10.0.0',
      'postcss': '^8.0.0',
      'tailwindcss': '^3.0.0',
      'typescript': '^5.0.0'
    }
  }, null, 2);
}

function generateReadme(projectName: string) {
  return `# ${projectName}

Generated with BuildFlow

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

## Deploy on Vercel

The easiest way to deploy your Next.js app is to use the [Vercel Platform](https://vercel.com/new).
`;
}

function generateTailwindConfig() {
  return `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`;
}

function generateGitignore() {
  return `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts`;
}
