import Link from 'next/link'
import { Sparkles } from 'lucide-react'
import PricingCard from '@/components/PricingCard'

const PLANS = {
  FREE: {
    name: 'Free',
    price: 0,
    priceId: null,
    features: [
      '3 AI generations per month',
      'Save up to 5 projects',
      'Basic templates',
      'Community support'
    ]
  },
  PRO: {
    name: 'Pro',
    price: 19,
    priceId: process.env.STRIPE_PRO_PRICE_ID,
    features: [
      '100 AI generations per month',
      'Unlimited saved projects',
      'All premium templates',
      'AI chat refinements',
      'Priority support',
      'Export to multiple formats'
    ]
  },
  ENTERPRISE: {
    name: 'Enterprise',
    price: 99,
    priceId: process.env.STRIPE_ENTERPRISE_PRICE_ID,
    features: [
      'Unlimited AI generations',
      'Unlimited saved projects',
      'All templates & features',
      'Advanced AI models',
      'Custom branding',
      'API access',
      'Dedicated support',
      'Team collaboration'
    ]
  }
}

export default function Pricing() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-white to-blue-50">
      <header className="container mx-auto px-4 py-6">
        <nav className="flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <Sparkles className="w-8 h-8 text-purple-600" />
            <span className="text-2xl font-bold bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
              AI App Builder
            </span>
          </Link>
          <div className="flex items-center gap-4">
            <Link href="/auth/signin" className="text-gray-700 hover:text-purple-600 transition">
              Sign In
            </Link>
            <Link 
              href="/auth/signup"
              className="bg-gradient-to-r from-purple-600 to-blue-600 text-white px-6 py-2 rounded-lg hover:from-purple-700 hover:to-blue-700 transition"
            >
              Get Started
            </Link>
          </div>
        </nav>
      </header>

      <section className="container mx-auto px-4 py-20">
        <div className="text-center mb-16">
          <h1 className="text-5xl font-bold text-gray-900 mb-4">
            Simple, Transparent Pricing
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Choose the plan that's right for you. All plans include full access to our AI-powered builder.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
          <PricingCard
            name={PLANS.FREE.name}
            price={PLANS.FREE.price}
            priceId={PLANS.FREE.priceId}
            features={PLANS.FREE.features}
          />
          
          <PricingCard
            name={PLANS.PRO.name}
            price={PLANS.PRO.price}
            priceId={PLANS.PRO.priceId}
            features={PLANS.PRO.features}
            popular={true}
          />
          
          <PricingCard
            name={PLANS.ENTERPRISE.name}
            price={PLANS.ENTERPRISE.price}
            priceId={PLANS.ENTERPRISE.priceId}
            features={PLANS.ENTERPRISE.features}
          />
        </div>

        <div className="mt-20 max-w-3xl mx-auto">
          <h2 className="text-3xl font-bold text-center text-gray-900 mb-10">
            Frequently Asked Questions
          </h2>
          
          <div className="space-y-6">
            <div className="bg-white p-6 rounded-xl shadow-md">
              <h3 className="font-bold text-gray-900 mb-2">Can I cancel anytime?</h3>
              <p className="text-gray-600">
                Yes! You can cancel your subscription at any time. You'll continue to have access until the end of your billing period.
              </p>
            </div>

            <div className="bg-white p-6 rounded-xl shadow-md">
              <h3 className="font-bold text-gray-900 mb-2">What happens if I exceed my generation limit?</h3>
              <p className="text-gray-600">
                If you reach your monthly generation limit, you can either wait until the next billing cycle or upgrade to a higher plan for more generations.
              </p>
            </div>

            <div className="bg-white p-6 rounded-xl shadow-md">
              <h3 className="font-bold text-gray-900 mb-2">Do I own the code that's generated?</h3>
              <p className="text-gray-600">
                Absolutely! All code generated by our AI is 100% yours. You can use it however you want with no restrictions.
              </p>
            </div>

            <div className="bg-white p-6 rounded-xl shadow-md">
              <h3 className="font-bold text-gray-900 mb-2">Can I upgrade or downgrade my plan?</h3>
              <p className="text-gray-600">
                Yes, you can change your plan at any time. Upgrades are prorated, and downgrades take effect at the start of your next billing cycle.
              </p>
            </div>

            <div className="bg-white p-6 rounded-xl shadow-md">
              <h3 className="font-bold text-gray-900 mb-2">Is there a free trial?</h3>
              <p className="text-gray-600">
                Our Free plan gives you 3 generations per month with no credit card required. It's a great way to try out the platform!
              </p>
            </div>
          </div>
        </div>
      </section>

      <footer className="container mx-auto px-4 py-8 border-t border-gray-200">
        <div className="text-center text-gray-600">
          <p>© 2025 AI App Builder. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}